---
# Folders
- name: Create packer payload directories
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/{{ item.0.name }}/{{ item.1 }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'
    recurse: yes
  with_nested:
  - "{{ packer_builds }}"
  - "{{ build_paths }}"
  tags:
  - packer_prerequisites
  - packer_payload_directory

# Http files: Metadata
- name: Create empty meta-data file
  file:
    path: "/home/{{ ansible_user }}/{{ item.name }}/http/meta-data"
    state: touch
  loop: "{{ packer_builds }}"
  tags:
  - packer_prerequisites
  - packer_payload_metadata

# Scripts
- name: Copy payload specific build scripts
  ansible.builtin.copy:
    src: "{{ item.name }}/provisioner.sh"
    dest: "/home/{{ ansible_user }}/{{ item.name }}/scripts/provisioner.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '755'
  loop: "{{ packer_builds }}"
  tags:
  - packer_prerequisites
  - packer_payload_build_scripts

# Packer: vcenter
- name: Generate payload specific packer vcenter file
  ansible.builtin.template:
    src: "vcenter.pkr.hcl.jinja2"
    dest: "/home/{{ ansible_user }}/{{ item.name }}/vcenter.pkr.hcl"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '755'
  loop: "{{ packer_builds }}"
  tags:
  - packer_prerequisites
  - packer_payload_vars

# Packer: vars
- name: Generate payload specific packer vars file
  ansible.builtin.template:
    src: "variables.pkr.hcl.jinja2"
    dest: "/home/{{ ansible_user }}/{{ item.name }}/variables.pkr.hcl"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '755'
  loop: "{{ packer_builds }}"
  tags:
  - packer_prerequisites
  - packer_payload_vars

# Packer: user-data
- name: Generate payload specific packer http user-data file
  ansible.builtin.template:
    src: "user-data.jinja2"
    dest: "/home/{{ ansible_user }}/{{ item.name }}/http/user-data"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '755'
  loop: "{{ packer_builds }}"
  tags:
  - packer_prerequisites
  - packer_payload_userdata

# Packer: user-data
- name: Generate payload specific packer build.pkr.hcl file
  ansible.builtin.template:
    src: "build.pkr.hcl.jinja2"
    dest: "/home/{{ ansible_user }}/{{ item.name }}/build.pkr.hcl"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '755'
  loop: "{{ packer_builds }}"
  tags:
  - packer_prerequisites
  - packer_payload_build

# Packer validate files
- name: Validate builds
  shell:
    cmd: "packer validate -var-file vcenter.pkr.hcl -var-file variables.pkr.hcl build.pkr.hcl"
    chdir: "/home/{{ ansible_user }}/{{ item.name }}"
  loop: "{{ packer_builds }}"
  tags:
  - packer_prerequisites
  - packer_payload_validation